# Generated by Django 2.2.28 on 2026-03-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roamify', '0003_auto_20260326_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('landmarks', 'Landmarks'), ('urban', 'Urban'), ('beach', 'Beach'), ('nature', 'Nature')], default='landmarks', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
