# Generated by Django 2.2.28 on 2026-03-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roamify', '0004_auto_20260326_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
